apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mars-deploy
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: myapp-container
          image: busybox:1.28
          command: [ 'sh', '-c', 'echo The app is running! && sleep 60' ]
      containers:
        - name: nginx
          image: nginx:1.14.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: mars-deploy
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
